server:
  port: 8080

spring:
  profiles:
    include: Netty

# ????
logging:
  level:
    # web??
    org.springframework.web: debug
    # security ??
    org.springframework.security: error
    # mybatis??
    org.mybatis: debug
    io.netty: info
    io.netty.handler.logging: debug
    com.example.nettyboot: info
  charset:
    # ???????
    console: UTF-8
    # ??????
    file: UTF-8
  # ??????????????????
  file:
    # ???????????????????????????????max-file-size,???file-name-pattern????
    # ???log/ota.log????????????????????????????/log/ota.log?????????????????
    name: log/ota.log
  logback:
    rollingpolicy:
      # ?????????10M, ?????????????
      max-file-size: 1MB
      # ???????
      max-history: 30
      # ??????,??? ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz,??????????/???.%i.????,??%i????????????
      # ??? ????2021/11/5 ,????????? log/ota.2021-11-05.0.gz,0???????????????1,2,3...
      # ??????????????log/ota.2021-11-05.0?????
      # ????????????: log/2021-11/ota.2020-11-5.0.log?????????
      file-name-pattern: log/%d{yyyy-MM}/ota.%d{yyyy-MM-dd}.%i.log
